apps/quick-learn-backend/src/entities/course.entity.ts
apps/quick-learn-backend/src/entities/user.entity.ts
apps/quick-learn-backend/src/lang/en.ts
apps/quick-learn-backend/src/routes/course/course.controller.ts
apps/quick-learn-backend/src/routes/course/course.service.ts
apps/quick-learn-backend/src/routes/course/dto/course-archive.dto.ts
apps/quick-learn-backend/src/routes/lesson/lesson.controller.ts
apps/quick-learn-backend/src/routes/lesson/lesson.service.ts
apps/quick-learn-backend/src/routes/roadmap/dto/activate-roadmap.dto.ts
apps/quick-learn-backend/src/routes/roadmap/dto/update-roadmap.dto.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.controller.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts
apps/quick-learn-backend/src/routes/users/users.controller.ts
apps/quick-learn-frontend/src/apiServices/archivedService.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/courses/ArchivedCourses.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/courses/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/lessons/ArchivedLessons.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/lessons/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/roadmaps/ArchivedRoadmaps.tsx
apps/quick-learn-frontend/src/constants/api.enum.ts
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/ViewLesson.tsx
apps/quick-learn-frontend/src/shared/types/contentRepository.ts

This PR implements archive functionality for lessons and courses, including list views with infinite scroll pagination, restore capabilities, and proper user tracking.
- Added `ArchivedLessons.tsx` component
- Infinite scroll pagination
- Search functionality
- Restore/delete modal confirmations
- User tracking for archive actions
- Updated API enum constants
```typescript
export enum ArchivedApiEnum {
// Existing endpoints...
ARCHIVED_LESSONS = '/lesson/archived',
ACTIVATE_LESSON = '/lesson/activate',
ARCHIVED_COURSES = '/course/archived',
ACTIVATE_COURSE = '/course/activate',
}
```
- Added archive-related translations to `en.ts`
```typescript
archivedLessons: 'Archived Lessons',
archivedLessonsSubtext: 'Following lessons have been archived.',
confirmActivateLesson: 'Are you sure you …
```

Feature archived

---

apps/quick-learn-backend/src/routes/course/course.controller.ts
apps/quick-learn-backend/src/routes/course/course.service.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.controller.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/community/CommunityCourseRepo.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/community/CourseCard.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/community/[course]/CommunityCourse.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/Card.tsx
apps/quick-learn-frontend/src/shared/components/CreateNewCard.tsx

This commit consist of Bug Fixes also enhancement of Card Component as per requirements

Bugs fixed as per the feedback

---

apps/quick-learn-frontend/src/shared/components/Navbar.tsx

This PR includes the fixes for the navbar alignments.

Fix: made the navbar items to align center for the large screens

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/Dashboard.tsx
apps/quick-learn-frontend/src/app/global.css
apps/quick-learn-frontend/src/shared/components/ProgressCard.tsx

fix: Image resizing and added text decorator to learning path cards

---

apps/quick-learn-backend/src/routes/lesson/lesson.controller.ts
apps/quick-learn-backend/src/routes/lesson/lesson.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/approvals/approvalList.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts

This PR includes the fix for the listing of the approvals.

Enhance: added listing fixes on approvals

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx

fix: bugs QL-178, QL-177

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx
apps/quick-learn-frontend/src/store/features/teamSlice.ts

QL-172 Total Team Members Count Fixed in Team listing

---

apps/quick-learn-backend/src/common/decorators/public.decorator.ts
apps/quick-learn-backend/src/common/decorators/roles.decorator.ts
apps/quick-learn-backend/src/common/enum/user_role.enum.ts
apps/quick-learn-backend/src/routes/auth/guards/roles.guard.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/shared/formElements/ImageInput.tsx

FIX : data not getting reloaded due to redux fixed

---

apps/quick-learn-frontend/src/store/provider.tsx

FIX : Redux Hydration Issue Fixed

---

apps/quick-learn-backend/src/routes/auth/auth.service.ts
apps/quick-learn-backend/src/routes/lesson-progress/lesson-progress.controller.ts
apps/quick-learn-backend/src/routes/profile/profile.service.ts
apps/quick-learn-backend/src/routes/users/users.controller.ts
apps/quick-learn-backend/src/routes/users/users.service.ts
apps/quick-learn-frontend/src/apiServices/learningPathService.ts
apps/quick-learn-frontend/src/apiServices/lessonsService.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/Dashboard.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/RoadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/CourseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/[roadmap]/[course]/[lesson]/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/[roadmap]/[course]/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/[roadmap]/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/teamMemberDetails.tsx
apps/quick-learn-frontend/src/constants/api.enum.ts
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/ProgressCard.tsx
apps/quick-learn-frontend/src/shared/types/userTypes.ts
apps/quick-learn-frontend/src/utils/helpers.ts

Team routes

---

apps/quick-learn-backend/src/routes/users/users.controller.ts
apps/quick-learn-frontend/src/apiServices/archivedService.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/users/ArchivedUsers.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/RoadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/CourseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/teamMemberDetails.tsx
apps/quick-learn-frontend/src/store/features/archivedSlice.ts
apps/quick-learn-frontend/src/store/features/teamSlice.ts

Bug fixes 23

---

apps/quick-learn-frontend/src/shared/formElements/ImageInput.tsx

FIX: User Context updated after user profile image is updated

---

apps/quick-learn-backend/src/routes/users/users.controller.ts
apps/quick-learn-frontend/src/apiServices/learningPathService.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/RoadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/CourseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx

fix/ Admin can view all the teams routes

---

apps/quick-learn-backend/src/routes/roadmap/roadmap.controller.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/teamMemberDetails.tsx
apps/quick-learn-frontend/src/shared/types/contentRepository.ts
apps/quick-learn-frontend/src/shared/types/userTypes.ts

Next sprint

---

apps/quick-learn-backend/src/routes/users/users.controller.ts
apps/quick-learn-backend/src/routes/users/users.service.ts
apps/quick-learn-frontend/src/apiServices/learningPathService.ts
apps/quick-learn-frontend/src/constants/api.enum.ts
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/Navbar.tsx
apps/quick-learn-frontend/src/shared/components/NavbarSearchBox.tsx
apps/quick-learn-frontend/src/shared/components/RouteTab.tsx
apps/quick-learn-frontend/src/shared/components/SearchBox.tsx
apps/quick-learn-frontend/src/shared/types/contentRepository.ts
apps/quick-learn-frontend/src/utils/helpers.ts

Search functionality

---

apps/quick-learn-backend/src/routes/lesson/lesson-email-cron.service.ts
apps/quick-learn-frontend/src/shared/modals/ActivityGraph.tsx

lesson name undefined fix

---

apps/quick-learn-frontend/src/app/(Auth)/forgot-password/ForgotPassword.tsx
apps/quick-learn-frontend/src/app/(Auth)/forgot-password/page.tsx
apps/quick-learn-frontend/src/shared/modals/ActivityGraph.tsx

QL-211 FIX AND USER ACTIVITY COLOR NORMALIZATION FIX

---

apps/quick-learn-frontend/src/shared/components/NavbarSearchBox.tsx
apps/quick-learn-frontend/src/shared/components/RouteTab.tsx
apps/quick-learn-frontend/src/shared/types/contentRepository.ts

Added history functionality on searchbar now

---

apps/quick-learn-backend/src/routes/lesson/lesson-email-cron.service.ts

ENV file issuse fix

---

apps/quick-learn-backend/src/routes/lesson/lesson-email-cron.service.ts

removed cron job

---

apps/quick-learn-backend/src/routes/lesson-progress/lesson-progress.controller.ts
apps/quick-learn-backend/src/routes/lesson/lesson-email-cron.service.ts
apps/quick-learn-frontend/src/apiServices/lessonsService.ts
apps/quick-learn-frontend/src/app/(Public)/daily-lesson/[lesson]/dailyLessonDetail.tsx

Public route created separate for user progress and mark complete

---

apps/quick-learn-backend/src/routes/lesson-progress/lesson-progress.controller.ts

fix/ bug markasdone

---

apps/quick-learn-backend/src/routes/lesson/lesson-email-cron.service.ts

Refactor: Lesson cronjob and disabled it on the dev env

---

apps/quick-learn-backend/src/routes/auth/auth.service.ts
apps/quick-learn-backend/src/routes/auth/strategies/jwt-refresh.strategy.ts
apps/quick-learn-backend/src/routes/course/course.service.ts
apps/quick-learn-backend/src/routes/lesson-progress/lesson-progress.service.ts
apps/quick-learn-backend/src/routes/lesson/lesson.service.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts
apps/quick-learn-backend/src/routes/skills/skills.service.ts
apps/quick-learn-backend/src/routes/team/team.service.ts
apps/quick-learn-backend/src/routes/users/users.service.ts

1. I refactor the if statement where we use multiple operator inside if statement.
2. The second thing is to remove the comments from the code.

refactorFixes

---

apps/quick-learn-backend/src/config/app.config.ts
apps/quick-learn-backend/src/routes/auth/auth.service.ts
apps/quick-learn-backend/src/routes/auth/strategies/jwt-refresh.strategy.ts
apps/quick-learn-backend/src/routes/course/course.service.ts
apps/quick-learn-backend/src/routes/lesson-progress/lesson-progress.service.ts
apps/quick-learn-backend/src/routes/lesson/lesson-email-cron.service.ts
apps/quick-learn-backend/src/routes/lesson/lesson.service.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts
apps/quick-learn-backend/src/routes/skills/skills.service.ts
apps/quick-learn-backend/src/routes/team/team.service.ts
apps/quick-learn-backend/src/routes/users/users.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/contentRepository.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx
apps/quick-learn-frontend/src/app/(Public)/daily-lesson/[lesson]/DailyLessonDetail.tsx

Dev to main

---

package-lock.json
package.json

Fix: packages

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/utils/helpers.ts

Refactor: LEARN29

---

apps/quick-learn-frontend/src/app/global.css
apps/quick-learn-frontend/src/shared/components/ViewLesson.tsx

Fix: Learn 44 Images overflowing in mobile screen.

---

apps/quick-learn-frontend/next.config.js
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx

Fix: LEARN-42 The Save button should get disabled if no roadmap is selected to assign/unassign

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/teamMemberDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/edit/[member]/AddUpdateMember.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/edit/[member]/MemberForm.tsx
apps/quick-learn-frontend/src/store/features/teamSlice.ts

Fix: LEARN-35 Multiple requests are sent to the network when selecting a filter option in the Team section.

---

.github/workflows/test.yml

Update GitHub Actions workflow to use pull_request_target and reference the correct branch

Fix: Github Actions

---

apps/quick-learn-frontend/src/shared/components/Editor.tsx
apps/quick-learn-frontend/src/shared/formElements/ImageInput.tsx

Fix: LEARN-43,65 error displayed while uploading the Image "Image should be less than 5MB", Same image upload won't update again if tried.

---

apps/quick-learn-backend/src/routes/cronjob/lesson-email-cron.service.ts

Fix: LEARN:59 Greeting issue in daily mail.

---

apps/quick-learn-backend/src/routes/roadmap-category/roadmap-category.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/contentRepository.tsx
apps/quick-learn-frontend/src/context/contextHelperService.ts
apps/quick-learn-frontend/src/context/userContext.tsx
apps/quick-learn-frontend/src/store/store.ts

fix: LEARN-62 Metadata is being persisted even when reloaded also fixed  the issue category without roadmap not being shown.

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/contentRepository.tsx

Hot fixes: metadata fetching in ContentRepository.

---

apps/quick-learn-frontend/next-env.d.ts
apps/quick-learn-frontend/src/shared/components/Navbar.tsx

Fix: LEARN-60 the signout

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx
apps/quick-learn-frontend/src/shared/formElements/ImageInput.tsx

Bug: Learn34 - Save button get enabled when we upload team logo and disabled when the logo is uploaded

---

apps/quick-learn-backend/src/routes/course/course.controller.ts
apps/quick-learn-backend/src/routes/course/course.service.ts
apps/quick-learn-backend/src/routes/users/dto/pagination.dto.ts
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx

fix: LEARN-48 Unapproval lessons being shown in Community course.

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/account-settings/BaseLayout.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx

Bug: Learn63-when we edit primary skills the validation work properly

---

apps/quick-learn-backend/src/lang/en.ts
apps/quick-learn-backend/src/routes/profile/profile.controller.ts
apps/quick-learn-backend/src/routes/profile/profile.service.ts
apps/quick-learn-frontend/next-env.d.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/profile-settings/change-password/ChangePassword.tsx
apps/quick-learn-frontend/src/shared/formElements/FormFieldsMapper.tsx
apps/quick-learn-frontend/src/shared/types/formTypes.ts

Added triggers which interact with confirm Password If it detects any change and displays error if needed.

Fix: LEARN-36 Change password shows error message with even a slight change

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/EmptyStatePlaceholder.tsx
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx

Enhancement: Learn 73 add type to buttons and add headings in courses and lesson pages

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/edit/[lesson]/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/view/[lesson]/lessonDetails.tsx

Enhancement:  LEARN-66 editor can edit his lesson even after sending for Approval

---

package-lock.json
package.json

Enhancement: Add sharp library for image processing

---

README.md
ecosystem.config.js
start-backend.sh

Chore: Update backend startup process with new script and permissions

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/flagged/flaggedList.tsx

Fix: updated the unflagged count at first load for listing

---

apps/quick-learn-backend/src/routes/lesson/lesson.service.ts

Fix: update lesson and course filtering to exclude archived entries

---

apps/quick-learn-backend/src/routes/cronjob/cronjob.controller.ts
apps/quick-learn-backend/src/routes/cronjob/leaderboard-cron.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx

Enhancement: LEADERBOARD Improved user experience and removed unecessary checks

---

apps/quick-learn-backend/src/routes/cronjob/leaderboard-cron.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts

Reverts cs-quicklabs/quick-learn#337

Revert "Fix:   hotfixes"

---

apps/quick-learn-backend/src/routes/cronjob/leaderboard-cron.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx

Pagination and ranking added fixed

---

apps/quick-learn-backend/src/routes/users/users.controller.ts

fix: Permission Issue for creating a new User

---

apps/quick-learn-backend/src/email-templates/leaderboard-template.mjml
apps/quick-learn-backend/src/routes/cronjob/leaderboard-cron.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/page.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts

fix: Leaderboard minor fixes and enhancements LEARN-98, LEARN-95

---

apps/quick-learn-frontend/src/shared/components/Editor.tsx

Bug: Learn-74 Scrolling issue while make any text heading or link

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/SkeletonLoader.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts

Enhancement: Added Learning score to the leaderboard table.

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/orphan-course/CourseTable.tsx

Fix:capitalised the first letter of orphan course name

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/approvals/approvalList.tsx

Fix: LEARN-106 first_name issue on Lesson Approval page

---

apps/quick-learn-backend/src/lang/en.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.controller.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts

fix: refactor: Message on assigning courses in roadmaps AND refactored roadmaps services backend.

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/approvals/ApprovalListSkeleton.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/flagged/flaggedSkeleton.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/orphan-course/Skeleton.tsx
apps/quick-learn-frontend/src/shared/components/EditorToolbar.tsx
apps/quick-learn-frontend/src/utils/HiLink.tsx

Refactor: Warning fixes

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/contentRepository.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/layout.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/Dashboard.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/RoadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/CourseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/teamMemberDetails.tsx
apps/quick-learn-frontend/src/shared/components/Breadcrumb.tsx
apps/quick-learn-frontend/src/shared/components/Card.tsx
apps/quick-learn-frontend/src/shared/components/Navbar.tsx
apps/quick-learn-frontend/src/shared/components/ProgressCard.tsx
apps/quick-learn-frontend/src/shared/components/SmallScreenTabs.tsx
apps/quick-learn-frontend/src/shared/components/ViewLesson.tsx
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx
apps/quick-learn-frontend/src/shared/pageTemplates/AuthTemplate.tsx

Bug: Mobile fixes

---

apps/quick-learn-backend/src/routes/course/course.controller.ts
apps/quick-learn-backend/src/routes/lesson/lesson.controller.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.controller.ts
apps/quick-learn-backend/src/routes/users/users.controller.ts
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/Navbar.tsx

Added archive menu items to admin role

---

apps/quick-learn-frontend/src/app/global.css
apps/quick-learn-frontend/src/shared/components/Breadcrumb.tsx
apps/quick-learn-frontend/src/shared/components/Editor.tsx
apps/quick-learn-frontend/src/shared/components/ViewLesson.tsx

Bug: Indentation fixes while viewing the lesson in learning path

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx
lib/shared/src/lib/shared.ts

fix: flicker to default value

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/orphan-course/CourseTable.tsx

Big: Minor Fixes

---

apps/quick-learn-frontend/next.config.js
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/roadmapDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/[member]/teamMemberDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/edit/[member]/MemberForm.tsx
apps/quick-learn-frontend/src/app/(Public)/daily-lesson/[token]/DailyLessonDetail.tsx
apps/quick-learn-frontend/src/app/global.css
apps/quick-learn-frontend/src/app/layout.tsx
apps/quick-learn-frontend/src/shared/components/Card.tsx
apps/quick-learn-frontend/src/shared/components/ProgressCard.tsx
apps/quick-learn-frontend/src/shared/components/Tooltip.tsx
apps/quick-learn-frontend/src/shared/modals/AccountSettiongConformationModal.tsx
apps/quick-learn-frontend/src/shared/modals/ActivityGraph.tsx
apps/quick-learn-frontend/src/shared/modals/addEditCourseModal.tsx
apps/quick-learn-frontend/src/shared/modals/addEditRoadMapModal.tsx
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx
apps/quick-learn-frontend/src/shared/modals/conformationModal.tsx
apps/quick-learn-frontend/tsconfig.json
package-lock.json
package.json

Refactor: Headless Ui

---

apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts

refactor: remove unnecessary left join for lessons in roadmap service

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/shared/components/Editor.tsx

Fix: Learn 109 when opening a lesson the update lesson call is being sent

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/account-settings/BaseLayout.tsx

Fix: LEARN-118 multiple request when deleted in Account section

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/shared/components/Editor.tsx

fix:editor

---

apps/quick-learn-backend/src/routes/course/course.controller.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.controller.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts
apps/quick-learn-frontend/src/apiServices/contentRepositoryService.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/courses/ArchivedCourses.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/courses/[course]/courseDetailSkeleton.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/courses/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/courses/[course]/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/layout.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/roadmaps/ArchivedRoadmaps.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/roadmaps/[roadmap]/page.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/roadmaps/[roadmap]/roadmapDetail.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/roadmaps/[roadmap]/roadmapDetailsSkeleton.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/ArchivedCell.tsx
apps/quick-learn-frontend/src/shared/components/ArchivedDialogBox.tsx

Enhancement: Learn 114

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/approvals/[lesson]/lessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/community/[course]/CommunityCourse.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/community/[course]/[lesson]/Lesson.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/view/[lesson]/lessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/flagged/[lesson]/lessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/app/(Public)/daily-lesson/[token]/DailyLessonDetail.tsx
apps/quick-learn-frontend/src/shared/components/LessonSkeleton.tsx

add LessonSkeleton component and integrate it into lesson detail views for an improved loading experience

fix: minor changes

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/courseDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/leaderboard/LeaderboardTable.tsx

fix: leaderboard Learning score, on delete navigation issue

---

apps/quick-learn-frontend/src/shared/components/Editor.tsx

fix: editor update request on opening the lesson

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/lessons/[lesson]/ViewArchivedLesson.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/archived/users/[user]/ViewArchivedUser.tsx
apps/quick-learn-frontend/src/shared/components/ArchivedCell.tsx
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx

1.  Loading is centered in AssignDataModal.
2. Truncate was fixed for Archived section.
3. Name was fixed on ViewArchivedUser page.
4. Added No data found on Archived user.

fix: Multiple Issues

---

apps/quick-learn-frontend/src/shared/components/Editor.tsx

feat: enhance image handling in editor with direct paste support

---

apps/quick-learn-backend/src/common/modules/lesson-token/lesson-token.service.ts
apps/quick-learn-backend/src/database/data-source.ts
apps/quick-learn-backend/src/database/migrations/1742364731131-migration.ts
apps/quick-learn-backend/src/entities/course.entity.ts
apps/quick-learn-backend/src/entities/leaderboard.entity.ts
apps/quick-learn-backend/src/entities/lesson-token.entity.ts
apps/quick-learn-backend/src/entities/lesson.entity.ts
apps/quick-learn-backend/src/entities/quarterly-leaderboard.entity.ts
apps/quick-learn-backend/src/entities/reset-token.entity.ts
apps/quick-learn-backend/src/entities/roadmap.entity.ts
apps/quick-learn-backend/src/entities/session.entity.ts
apps/quick-learn-backend/src/entities/user-lesson-progress.entity.ts
apps/quick-learn-backend/src/entities/user.entity.ts
apps/quick-learn-backend/src/routes/auth/auth.service.ts
apps/quick-learn-backend/src/routes/course/course.service.ts
apps/quick-learn-backend/src/routes/cronjob/lesson-email-cron.service.ts
apps/quick-learn-backend/src/routes/roadmap/roadmap.service.ts

Enhancement: Add migration and make changes in table name 

---

apps/quick-learn-frontend/src/app/layout.tsx
apps/quick-learn-frontend/src/app/page.tsx

add meta tags for SEO optimization and enhance page metadata for Quick Learn

chore: added metadata for better listing

---

apps/quick-learn-backend/src/routes/lesson/lesson.service.ts
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/learning-path/[roadmap]/[course]/[lesson]/LessonDetails.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/profile-settings/email-preference/EmailPreference.tsx
apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/teams/TeamMemberListing.tsx
apps/quick-learn-frontend/src/app/(Public)/daily-lesson/[token]/DailyLessonDetail.tsx
apps/quick-learn-frontend/src/app/layout.tsx
apps/quick-learn-frontend/src/shared/components/ActivityGraphWrapper.tsx
apps/quick-learn-frontend/src/shared/components/InputCheckbox.tsx
apps/quick-learn-frontend/src/shared/components/UIElements.tsx
apps/quick-learn-frontend/src/shared/components/ViewLesson.tsx
apps/quick-learn-frontend/src/shared/formElements/FormFieldsMapper.tsx
apps/quick-learn-frontend/src/shared/formElements/InputField.tsx
apps/quick-learn-frontend/src/shared/modals/assignDataModal.tsx

Bug: Checkbox, loader fixes.

---

apps/quick-learn-frontend/src/app/(Dashboard)/dashboard/content/[roadmap]/[course]/[lesson]/lesson.tsx
apps/quick-learn-frontend/src/constants/lang/en.ts
apps/quick-learn-frontend/src/shared/components/Breadcrumb.tsx

Enhancement: Draft lesson fix

---

apps/quick-learn-backend/src/common/modules/lesson-token/lesson-token.service.ts
apps/quick-learn-frontend/src/app/global.css
apps/quick-learn-frontend/src/shared/components/Editor.tsx

Lesson token service: only create leaderboard for the active users and update editor styles to fit the content when reading

fixes: Misc
